### ISSUE TITLE
Deposit ETH not work

### ISSUE THREAD

**Issue by go-apollyon** [InfraexDev/peatio#104]
Hi there, 

blockchain is sync, but deposit in peatio not present and in etherscan i see balance

**Comment by muhammednagy** [comment]
hey @shouton 
i've never encountered a problem with service.rb
it has been running on my clients servers for over 2 months without any problems
Sure there's a better solution sadly it's on nodejs only so i tried to use the ruby method

**Comment by shouton** [comment]
hi, @muhammednagy 

Yes, first at first.
service.rb works perfectly. you did a great work. bro, thanks a lot.

but, in my environment, it gets error after couple days. I am not sure, but i think it's the problem caused by nodejs, web3, and old version of ruby. Up to my opinion, those script languages are not reliable enough to run forever.

but, it was ok. I can handle it myself. fix it to fit my environment. I think it s


Next, another issue, I'm working on erc20, but have no ideas to deal with token transfer, it's different with ethereum.

```javascript
  for tx in block["transactions"]
  // unfortunately, no transaction of token in block["transactions"].
    if accounts.include? tx["to"]
      log.info(tx)
      postData = Net::HTTP.post_form(URI.parse('https://example.com/webhooks/${erc20_name}'), {'type'=>'transaction', 'hash'=>tx["hash"]})
    end
  end
```

What do you think?

**Comment by muhammednagy** [comment]
hi, @shouton 
you can change the number 
i added five as the block confirmations number.
you can make it whatever you want.
some exchanges require 50 like i think coinbase.

**Comment by shouton** [comment]
@muhammednagy 

I though, you tried to start search the transaction from -5 previous block, and end current block.
something like

```ruby
depth = 5    # -> i'll change it to 20
endblock = w3.eth_blockNumber
startblock = w3.eth_blockNumber - depth

for (i=startblock, i <= endblock, i++)
  block = '0x' + i.to_s(16)
  for tx in block["transactions"]
    if accounts.include? tx["to"]
      log.info(tx)
      postData = Net::HTTP.post_form(...
    end
  end
end // end of block 
``` 


I just don't understand how you can be sure that the tx will just stay in "w3.eth_blockNumber - 5".

Please correct me if i misunderstood something.


Regards with many thanks.

**Comment by muhammednagy** [comment]
Dude, it keeps moving from latest block to latest - 1 then -2 then -3 then -4 then -5 
Ethereum produces a block every 10 - 15 seconds.
We look more than once in less than that time.
Same case for 20
New blocks get added always thus it moves from latest block to latest - 5.
Hope you understood.
Let me know of it’s still unclear .
Thank you.

**Comment by shouton** [comment]
hi, @muhammednagy 

Understood. Thanks dude.
